/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SocialRouteImport } from './routes/social'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PractitionerSignupRouteImport } from './routes/practitioner.signup'
import { Route as PractitionerPendingRouteImport } from './routes/practitioner.pending'
import { Route as PractitionerOnboardingRouteImport } from './routes/practitioner.onboarding'
import { Route as PractitionerLoginRouteImport } from './routes/practitioner.login'
import { Route as PractitionerAppRouteImport } from './routes/practitioner.app'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ClientLoginRouteImport } from './routes/client.login'
import { Route as ClientAppRouteImport } from './routes/client.app'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAppRouteImport } from './routes/admin.app'
import { Route as ClientAppIndexRouteImport } from './routes/client.app.index'
import { Route as PractitionerAppSettingsRouteImport } from './routes/practitioner.app.settings'
import { Route as PractitionerAppProgramQueueRouteImport } from './routes/practitioner.app.program-queue'
import { Route as PractitionerAppProfileRouteImport } from './routes/practitioner.app.profile'
import { Route as PractitionerAppInsightsRouteImport } from './routes/practitioner.app.insights'
import { Route as PractitionerAppDashboardRouteImport } from './routes/practitioner.app.dashboard'
import { Route as PractitionerAppAlertsRouteImport } from './routes/practitioner.app.alerts'
import { Route as PractitionerAppAddClientRouteImport } from './routes/practitioner.app.add-client'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ClientAppYvesRouteImport } from './routes/client.app.yves'
import { Route as ClientAppTimelineRouteImport } from './routes/client.app.timeline'
import { Route as ClientAppProgressRouteImport } from './routes/client.app.progress'
import { Route as ClientAppProfileRouteImport } from './routes/client.app.profile'
import { Route as ClientAppCheckinRouteImport } from './routes/client.app.checkin'
import { Route as ApiPublicTriageQueryRouteImport } from './routes/api/public/triage-query'
import { Route as AdminAppSettingsRouteImport } from './routes/admin.app.settings'
import { Route as AdminAppProgramsRouteImport } from './routes/admin.app.programs'
import { Route as AdminAppPractitionersRouteImport } from './routes/admin.app.practitioners'
import { Route as AdminAppGradingRouteImport } from './routes/admin.app.grading'
import { Route as AdminAppDashboardRouteImport } from './routes/admin.app.dashboard'
import { Route as AdminAppClientsRouteImport } from './routes/admin.app.clients'
import { Route as AdminAppAlertsRouteImport } from './routes/admin.app.alerts'
import { Route as PractitionerAppClientDetailClientIdRouteImport } from './routes/practitioner.app.client-detail.$clientId'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksNightlyRiskAnalysisRouteImport } from './routes/api/public/hooks/nightly-risk-analysis'
import { Route as ApiPublicHooksCheckinRemindersRouteImport } from './routes/api/public/hooks/checkin-reminders'
import { Route as AdminAppPractitionerPractitionerIdRouteImport } from './routes/admin.app.practitioner.$practitionerId'
import { Route as AdminAppClientDetailClientIdRouteImport } from './routes/admin.app.client-detail.$clientId'
import { Route as ApiPublicWearablesPolarCallbackRouteImport } from './routes/api/public/wearables/polar/callback'
import { Route as ApiPublicWearablesOuraWebhookRouteImport } from './routes/api/public/wearables/oura/webhook'
import { Route as ApiPublicWearablesOuraCallbackRouteImport } from './routes/api/public/wearables/oura/callback'
import { Route as ApiPublicWearablesGarminWebhookRouteImport } from './routes/api/public/wearables/garmin/webhook'
import { Route as ApiPublicWearablesGarminCallbackRouteImport } from './routes/api/public/wearables/garmin/callback'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionerSignupRoute = PractitionerSignupRouteImport.update({
  id: '/practitioner/signup',
  path: '/practitioner/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionerPendingRoute = PractitionerPendingRouteImport.update({
  id: '/practitioner/pending',
  path: '/practitioner/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionerOnboardingRoute = PractitionerOnboardingRouteImport.update({
  id: '/practitioner/onboarding',
  path: '/practitioner/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionerLoginRoute = PractitionerLoginRouteImport.update({
  id: '/practitioner/login',
  path: '/practitioner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionerAppRoute = PractitionerAppRouteImport.update({
  id: '/practitioner/app',
  path: '/practitioner/app',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client/login',
  path: '/client/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAppRoute = ClientAppRouteImport.update({
  id: '/client/app',
  path: '/client/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppRoute = AdminAppRouteImport.update({
  id: '/admin/app',
  path: '/admin/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAppIndexRoute = ClientAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientAppRoute,
} as any)
const PractitionerAppSettingsRoute = PractitionerAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PractitionerAppRoute,
} as any)
const PractitionerAppProgramQueueRoute =
  PractitionerAppProgramQueueRouteImport.update({
    id: '/program-queue',
    path: '/program-queue',
    getParentRoute: () => PractitionerAppRoute,
  } as any)
const PractitionerAppProfileRoute = PractitionerAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PractitionerAppRoute,
} as any)
const PractitionerAppInsightsRoute = PractitionerAppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => PractitionerAppRoute,
} as any)
const PractitionerAppDashboardRoute =
  PractitionerAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => PractitionerAppRoute,
  } as any)
const PractitionerAppAlertsRoute = PractitionerAppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => PractitionerAppRoute,
} as any)
const PractitionerAppAddClientRoute =
  PractitionerAppAddClientRouteImport.update({
    id: '/add-client',
    path: '/add-client',
    getParentRoute: () => PractitionerAppRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAppYvesRoute = ClientAppYvesRouteImport.update({
  id: '/yves',
  path: '/yves',
  getParentRoute: () => ClientAppRoute,
} as any)
const ClientAppTimelineRoute = ClientAppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ClientAppRoute,
} as any)
const ClientAppProgressRoute = ClientAppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ClientAppRoute,
} as any)
const ClientAppProfileRoute = ClientAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientAppRoute,
} as any)
const ClientAppCheckinRoute = ClientAppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => ClientAppRoute,
} as any)
const ApiPublicTriageQueryRoute = ApiPublicTriageQueryRouteImport.update({
  id: '/api/public/triage-query',
  path: '/api/public/triage-query',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppSettingsRoute = AdminAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppProgramsRoute = AdminAppProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppPractitionersRoute = AdminAppPractitionersRouteImport.update({
  id: '/practitioners',
  path: '/practitioners',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppGradingRoute = AdminAppGradingRouteImport.update({
  id: '/grading',
  path: '/grading',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppDashboardRoute = AdminAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppClientsRoute = AdminAppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppAlertsRoute = AdminAppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminAppRoute,
} as any)
const PractitionerAppClientDetailClientIdRoute =
  PractitionerAppClientDetailClientIdRouteImport.update({
    id: '/client-detail/$clientId',
    path: '/client-detail/$clientId',
    getParentRoute: () => PractitionerAppRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNightlyRiskAnalysisRoute =
  ApiPublicHooksNightlyRiskAnalysisRouteImport.update({
    id: '/api/public/hooks/nightly-risk-analysis',
    path: '/api/public/hooks/nightly-risk-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckinRemindersRoute =
  ApiPublicHooksCheckinRemindersRouteImport.update({
    id: '/api/public/hooks/checkin-reminders',
    path: '/api/public/hooks/checkin-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAppPractitionerPractitionerIdRoute =
  AdminAppPractitionerPractitionerIdRouteImport.update({
    id: '/practitioner/$practitionerId',
    path: '/practitioner/$practitionerId',
    getParentRoute: () => AdminAppRoute,
  } as any)
const AdminAppClientDetailClientIdRoute =
  AdminAppClientDetailClientIdRouteImport.update({
    id: '/client-detail/$clientId',
    path: '/client-detail/$clientId',
    getParentRoute: () => AdminAppRoute,
  } as any)
const ApiPublicWearablesPolarCallbackRoute =
  ApiPublicWearablesPolarCallbackRouteImport.update({
    id: '/api/public/wearables/polar/callback',
    path: '/api/public/wearables/polar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWearablesOuraWebhookRoute =
  ApiPublicWearablesOuraWebhookRouteImport.update({
    id: '/api/public/wearables/oura/webhook',
    path: '/api/public/wearables/oura/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWearablesOuraCallbackRoute =
  ApiPublicWearablesOuraCallbackRouteImport.update({
    id: '/api/public/wearables/oura/callback',
    path: '/api/public/wearables/oura/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWearablesGarminWebhookRoute =
  ApiPublicWearablesGarminWebhookRouteImport.update({
    id: '/api/public/wearables/garmin/webhook',
    path: '/api/public/wearables/garmin/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWearablesGarminCallbackRoute =
  ApiPublicWearablesGarminCallbackRouteImport.update({
    id: '/api/public/wearables/garmin/callback',
    path: '/api/public/wearables/garmin/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/marketing': typeof MarketingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/social': typeof SocialRoute
  '/support': typeof SupportRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/app': typeof AdminAppRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/client/app': typeof ClientAppRouteWithChildren
  '/client/login': typeof ClientLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/practitioner/app': typeof PractitionerAppRouteWithChildren
  '/practitioner/login': typeof PractitionerLoginRoute
  '/practitioner/onboarding': typeof PractitionerOnboardingRoute
  '/practitioner/pending': typeof PractitionerPendingRoute
  '/practitioner/signup': typeof PractitionerSignupRoute
  '/admin/app/alerts': typeof AdminAppAlertsRoute
  '/admin/app/clients': typeof AdminAppClientsRoute
  '/admin/app/dashboard': typeof AdminAppDashboardRoute
  '/admin/app/grading': typeof AdminAppGradingRoute
  '/admin/app/practitioners': typeof AdminAppPractitionersRoute
  '/admin/app/programs': typeof AdminAppProgramsRoute
  '/admin/app/settings': typeof AdminAppSettingsRoute
  '/api/public/triage-query': typeof ApiPublicTriageQueryRoute
  '/client/app/checkin': typeof ClientAppCheckinRoute
  '/client/app/profile': typeof ClientAppProfileRoute
  '/client/app/progress': typeof ClientAppProgressRoute
  '/client/app/timeline': typeof ClientAppTimelineRoute
  '/client/app/yves': typeof ClientAppYvesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/practitioner/app/add-client': typeof PractitionerAppAddClientRoute
  '/practitioner/app/alerts': typeof PractitionerAppAlertsRoute
  '/practitioner/app/dashboard': typeof PractitionerAppDashboardRoute
  '/practitioner/app/insights': typeof PractitionerAppInsightsRoute
  '/practitioner/app/profile': typeof PractitionerAppProfileRoute
  '/practitioner/app/program-queue': typeof PractitionerAppProgramQueueRoute
  '/practitioner/app/settings': typeof PractitionerAppSettingsRoute
  '/client/app/': typeof ClientAppIndexRoute
  '/admin/app/client-detail/$clientId': typeof AdminAppClientDetailClientIdRoute
  '/admin/app/practitioner/$practitionerId': typeof AdminAppPractitionerPractitionerIdRoute
  '/api/public/hooks/checkin-reminders': typeof ApiPublicHooksCheckinRemindersRoute
  '/api/public/hooks/nightly-risk-analysis': typeof ApiPublicHooksNightlyRiskAnalysisRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/practitioner/app/client-detail/$clientId': typeof PractitionerAppClientDetailClientIdRoute
  '/api/public/wearables/garmin/callback': typeof ApiPublicWearablesGarminCallbackRoute
  '/api/public/wearables/garmin/webhook': typeof ApiPublicWearablesGarminWebhookRoute
  '/api/public/wearables/oura/callback': typeof ApiPublicWearablesOuraCallbackRoute
  '/api/public/wearables/oura/webhook': typeof ApiPublicWearablesOuraWebhookRoute
  '/api/public/wearables/polar/callback': typeof ApiPublicWearablesPolarCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/marketing': typeof MarketingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/social': typeof SocialRoute
  '/support': typeof SupportRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/app': typeof AdminAppRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/client/login': typeof ClientLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/practitioner/app': typeof PractitionerAppRouteWithChildren
  '/practitioner/login': typeof PractitionerLoginRoute
  '/practitioner/onboarding': typeof PractitionerOnboardingRoute
  '/practitioner/pending': typeof PractitionerPendingRoute
  '/practitioner/signup': typeof PractitionerSignupRoute
  '/admin/app/alerts': typeof AdminAppAlertsRoute
  '/admin/app/clients': typeof AdminAppClientsRoute
  '/admin/app/dashboard': typeof AdminAppDashboardRoute
  '/admin/app/grading': typeof AdminAppGradingRoute
  '/admin/app/practitioners': typeof AdminAppPractitionersRoute
  '/admin/app/programs': typeof AdminAppProgramsRoute
  '/admin/app/settings': typeof AdminAppSettingsRoute
  '/api/public/triage-query': typeof ApiPublicTriageQueryRoute
  '/client/app/checkin': typeof ClientAppCheckinRoute
  '/client/app/profile': typeof ClientAppProfileRoute
  '/client/app/progress': typeof ClientAppProgressRoute
  '/client/app/timeline': typeof ClientAppTimelineRoute
  '/client/app/yves': typeof ClientAppYvesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/practitioner/app/add-client': typeof PractitionerAppAddClientRoute
  '/practitioner/app/alerts': typeof PractitionerAppAlertsRoute
  '/practitioner/app/dashboard': typeof PractitionerAppDashboardRoute
  '/practitioner/app/insights': typeof PractitionerAppInsightsRoute
  '/practitioner/app/profile': typeof PractitionerAppProfileRoute
  '/practitioner/app/program-queue': typeof PractitionerAppProgramQueueRoute
  '/practitioner/app/settings': typeof PractitionerAppSettingsRoute
  '/client/app': typeof ClientAppIndexRoute
  '/admin/app/client-detail/$clientId': typeof AdminAppClientDetailClientIdRoute
  '/admin/app/practitioner/$practitionerId': typeof AdminAppPractitionerPractitionerIdRoute
  '/api/public/hooks/checkin-reminders': typeof ApiPublicHooksCheckinRemindersRoute
  '/api/public/hooks/nightly-risk-analysis': typeof ApiPublicHooksNightlyRiskAnalysisRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/practitioner/app/client-detail/$clientId': typeof PractitionerAppClientDetailClientIdRoute
  '/api/public/wearables/garmin/callback': typeof ApiPublicWearablesGarminCallbackRoute
  '/api/public/wearables/garmin/webhook': typeof ApiPublicWearablesGarminWebhookRoute
  '/api/public/wearables/oura/callback': typeof ApiPublicWearablesOuraCallbackRoute
  '/api/public/wearables/oura/webhook': typeof ApiPublicWearablesOuraWebhookRoute
  '/api/public/wearables/polar/callback': typeof ApiPublicWearablesPolarCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/marketing': typeof MarketingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/social': typeof SocialRoute
  '/support': typeof SupportRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/app': typeof AdminAppRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/client/app': typeof ClientAppRouteWithChildren
  '/client/login': typeof ClientLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/practitioner/app': typeof PractitionerAppRouteWithChildren
  '/practitioner/login': typeof PractitionerLoginRoute
  '/practitioner/onboarding': typeof PractitionerOnboardingRoute
  '/practitioner/pending': typeof PractitionerPendingRoute
  '/practitioner/signup': typeof PractitionerSignupRoute
  '/admin/app/alerts': typeof AdminAppAlertsRoute
  '/admin/app/clients': typeof AdminAppClientsRoute
  '/admin/app/dashboard': typeof AdminAppDashboardRoute
  '/admin/app/grading': typeof AdminAppGradingRoute
  '/admin/app/practitioners': typeof AdminAppPractitionersRoute
  '/admin/app/programs': typeof AdminAppProgramsRoute
  '/admin/app/settings': typeof AdminAppSettingsRoute
  '/api/public/triage-query': typeof ApiPublicTriageQueryRoute
  '/client/app/checkin': typeof ClientAppCheckinRoute
  '/client/app/profile': typeof ClientAppProfileRoute
  '/client/app/progress': typeof ClientAppProgressRoute
  '/client/app/timeline': typeof ClientAppTimelineRoute
  '/client/app/yves': typeof ClientAppYvesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/practitioner/app/add-client': typeof PractitionerAppAddClientRoute
  '/practitioner/app/alerts': typeof PractitionerAppAlertsRoute
  '/practitioner/app/dashboard': typeof PractitionerAppDashboardRoute
  '/practitioner/app/insights': typeof PractitionerAppInsightsRoute
  '/practitioner/app/profile': typeof PractitionerAppProfileRoute
  '/practitioner/app/program-queue': typeof PractitionerAppProgramQueueRoute
  '/practitioner/app/settings': typeof PractitionerAppSettingsRoute
  '/client/app/': typeof ClientAppIndexRoute
  '/admin/app/client-detail/$clientId': typeof AdminAppClientDetailClientIdRoute
  '/admin/app/practitioner/$practitionerId': typeof AdminAppPractitionerPractitionerIdRoute
  '/api/public/hooks/checkin-reminders': typeof ApiPublicHooksCheckinRemindersRoute
  '/api/public/hooks/nightly-risk-analysis': typeof ApiPublicHooksNightlyRiskAnalysisRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/practitioner/app/client-detail/$clientId': typeof PractitionerAppClientDetailClientIdRoute
  '/api/public/wearables/garmin/callback': typeof ApiPublicWearablesGarminCallbackRoute
  '/api/public/wearables/garmin/webhook': typeof ApiPublicWearablesGarminWebhookRoute
  '/api/public/wearables/oura/callback': typeof ApiPublicWearablesOuraCallbackRoute
  '/api/public/wearables/oura/webhook': typeof ApiPublicWearablesOuraWebhookRoute
  '/api/public/wearables/polar/callback': typeof ApiPublicWearablesPolarCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/marketing'
    | '/privacy-policy'
    | '/social'
    | '/support'
    | '/unsubscribe'
    | '/admin/app'
    | '/admin/login'
    | '/auth/callback'
    | '/client/app'
    | '/client/login'
    | '/email/unsubscribe'
    | '/practitioner/app'
    | '/practitioner/login'
    | '/practitioner/onboarding'
    | '/practitioner/pending'
    | '/practitioner/signup'
    | '/admin/app/alerts'
    | '/admin/app/clients'
    | '/admin/app/dashboard'
    | '/admin/app/grading'
    | '/admin/app/practitioners'
    | '/admin/app/programs'
    | '/admin/app/settings'
    | '/api/public/triage-query'
    | '/client/app/checkin'
    | '/client/app/profile'
    | '/client/app/progress'
    | '/client/app/timeline'
    | '/client/app/yves'
    | '/lovable/email/suppression'
    | '/practitioner/app/add-client'
    | '/practitioner/app/alerts'
    | '/practitioner/app/dashboard'
    | '/practitioner/app/insights'
    | '/practitioner/app/profile'
    | '/practitioner/app/program-queue'
    | '/practitioner/app/settings'
    | '/client/app/'
    | '/admin/app/client-detail/$clientId'
    | '/admin/app/practitioner/$practitionerId'
    | '/api/public/hooks/checkin-reminders'
    | '/api/public/hooks/nightly-risk-analysis'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/practitioner/app/client-detail/$clientId'
    | '/api/public/wearables/garmin/callback'
    | '/api/public/wearables/garmin/webhook'
    | '/api/public/wearables/oura/callback'
    | '/api/public/wearables/oura/webhook'
    | '/api/public/wearables/polar/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/marketing'
    | '/privacy-policy'
    | '/social'
    | '/support'
    | '/unsubscribe'
    | '/admin/app'
    | '/admin/login'
    | '/auth/callback'
    | '/client/login'
    | '/email/unsubscribe'
    | '/practitioner/app'
    | '/practitioner/login'
    | '/practitioner/onboarding'
    | '/practitioner/pending'
    | '/practitioner/signup'
    | '/admin/app/alerts'
    | '/admin/app/clients'
    | '/admin/app/dashboard'
    | '/admin/app/grading'
    | '/admin/app/practitioners'
    | '/admin/app/programs'
    | '/admin/app/settings'
    | '/api/public/triage-query'
    | '/client/app/checkin'
    | '/client/app/profile'
    | '/client/app/progress'
    | '/client/app/timeline'
    | '/client/app/yves'
    | '/lovable/email/suppression'
    | '/practitioner/app/add-client'
    | '/practitioner/app/alerts'
    | '/practitioner/app/dashboard'
    | '/practitioner/app/insights'
    | '/practitioner/app/profile'
    | '/practitioner/app/program-queue'
    | '/practitioner/app/settings'
    | '/client/app'
    | '/admin/app/client-detail/$clientId'
    | '/admin/app/practitioner/$practitionerId'
    | '/api/public/hooks/checkin-reminders'
    | '/api/public/hooks/nightly-risk-analysis'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/practitioner/app/client-detail/$clientId'
    | '/api/public/wearables/garmin/callback'
    | '/api/public/wearables/garmin/webhook'
    | '/api/public/wearables/oura/callback'
    | '/api/public/wearables/oura/webhook'
    | '/api/public/wearables/polar/callback'
  id:
    | '__root__'
    | '/'
    | '/marketing'
    | '/privacy-policy'
    | '/social'
    | '/support'
    | '/unsubscribe'
    | '/admin/app'
    | '/admin/login'
    | '/auth/callback'
    | '/client/app'
    | '/client/login'
    | '/email/unsubscribe'
    | '/practitioner/app'
    | '/practitioner/login'
    | '/practitioner/onboarding'
    | '/practitioner/pending'
    | '/practitioner/signup'
    | '/admin/app/alerts'
    | '/admin/app/clients'
    | '/admin/app/dashboard'
    | '/admin/app/grading'
    | '/admin/app/practitioners'
    | '/admin/app/programs'
    | '/admin/app/settings'
    | '/api/public/triage-query'
    | '/client/app/checkin'
    | '/client/app/profile'
    | '/client/app/progress'
    | '/client/app/timeline'
    | '/client/app/yves'
    | '/lovable/email/suppression'
    | '/practitioner/app/add-client'
    | '/practitioner/app/alerts'
    | '/practitioner/app/dashboard'
    | '/practitioner/app/insights'
    | '/practitioner/app/profile'
    | '/practitioner/app/program-queue'
    | '/practitioner/app/settings'
    | '/client/app/'
    | '/admin/app/client-detail/$clientId'
    | '/admin/app/practitioner/$practitionerId'
    | '/api/public/hooks/checkin-reminders'
    | '/api/public/hooks/nightly-risk-analysis'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/practitioner/app/client-detail/$clientId'
    | '/api/public/wearables/garmin/callback'
    | '/api/public/wearables/garmin/webhook'
    | '/api/public/wearables/oura/callback'
    | '/api/public/wearables/oura/webhook'
    | '/api/public/wearables/polar/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketingRoute: typeof MarketingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SocialRoute: typeof SocialRoute
  SupportRoute: typeof SupportRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminAppRoute: typeof AdminAppRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ClientAppRoute: typeof ClientAppRouteWithChildren
  ClientLoginRoute: typeof ClientLoginRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PractitionerAppRoute: typeof PractitionerAppRouteWithChildren
  PractitionerLoginRoute: typeof PractitionerLoginRoute
  PractitionerOnboardingRoute: typeof PractitionerOnboardingRoute
  PractitionerPendingRoute: typeof PractitionerPendingRoute
  PractitionerSignupRoute: typeof PractitionerSignupRoute
  ApiPublicTriageQueryRoute: typeof ApiPublicTriageQueryRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksCheckinRemindersRoute: typeof ApiPublicHooksCheckinRemindersRoute
  ApiPublicHooksNightlyRiskAnalysisRoute: typeof ApiPublicHooksNightlyRiskAnalysisRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicWearablesGarminCallbackRoute: typeof ApiPublicWearablesGarminCallbackRoute
  ApiPublicWearablesGarminWebhookRoute: typeof ApiPublicWearablesGarminWebhookRoute
  ApiPublicWearablesOuraCallbackRoute: typeof ApiPublicWearablesOuraCallbackRoute
  ApiPublicWearablesOuraWebhookRoute: typeof ApiPublicWearablesOuraWebhookRoute
  ApiPublicWearablesPolarCallbackRoute: typeof ApiPublicWearablesPolarCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioner/signup': {
      id: '/practitioner/signup'
      path: '/practitioner/signup'
      fullPath: '/practitioner/signup'
      preLoaderRoute: typeof PractitionerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioner/pending': {
      id: '/practitioner/pending'
      path: '/practitioner/pending'
      fullPath: '/practitioner/pending'
      preLoaderRoute: typeof PractitionerPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioner/onboarding': {
      id: '/practitioner/onboarding'
      path: '/practitioner/onboarding'
      fullPath: '/practitioner/onboarding'
      preLoaderRoute: typeof PractitionerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioner/login': {
      id: '/practitioner/login'
      path: '/practitioner/login'
      fullPath: '/practitioner/login'
      preLoaderRoute: typeof PractitionerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioner/app': {
      id: '/practitioner/app'
      path: '/practitioner/app'
      fullPath: '/practitioner/app'
      preLoaderRoute: typeof PractitionerAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/login': {
      id: '/client/login'
      path: '/client/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/app': {
      id: '/client/app'
      path: '/client/app'
      fullPath: '/client/app'
      preLoaderRoute: typeof ClientAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/app': {
      id: '/admin/app'
      path: '/admin/app'
      fullPath: '/admin/app'
      preLoaderRoute: typeof AdminAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/app/': {
      id: '/client/app/'
      path: '/'
      fullPath: '/client/app/'
      preLoaderRoute: typeof ClientAppIndexRouteImport
      parentRoute: typeof ClientAppRoute
    }
    '/practitioner/app/settings': {
      id: '/practitioner/app/settings'
      path: '/settings'
      fullPath: '/practitioner/app/settings'
      preLoaderRoute: typeof PractitionerAppSettingsRouteImport
      parentRoute: typeof PractitionerAppRoute
    }
    '/practitioner/app/program-queue': {
      id: '/practitioner/app/program-queue'
      path: '/program-queue'
      fullPath: '/practitioner/app/program-queue'
      preLoaderRoute: typeof PractitionerAppProgramQueueRouteImport
      parentRoute: typeof PractitionerAppRoute
    }
    '/practitioner/app/profile': {
      id: '/practitioner/app/profile'
      path: '/profile'
      fullPath: '/practitioner/app/profile'
      preLoaderRoute: typeof PractitionerAppProfileRouteImport
      parentRoute: typeof PractitionerAppRoute
    }
    '/practitioner/app/insights': {
      id: '/practitioner/app/insights'
      path: '/insights'
      fullPath: '/practitioner/app/insights'
      preLoaderRoute: typeof PractitionerAppInsightsRouteImport
      parentRoute: typeof PractitionerAppRoute
    }
    '/practitioner/app/dashboard': {
      id: '/practitioner/app/dashboard'
      path: '/dashboard'
      fullPath: '/practitioner/app/dashboard'
      preLoaderRoute: typeof PractitionerAppDashboardRouteImport
      parentRoute: typeof PractitionerAppRoute
    }
    '/practitioner/app/alerts': {
      id: '/practitioner/app/alerts'
      path: '/alerts'
      fullPath: '/practitioner/app/alerts'
      preLoaderRoute: typeof PractitionerAppAlertsRouteImport
      parentRoute: typeof PractitionerAppRoute
    }
    '/practitioner/app/add-client': {
      id: '/practitioner/app/add-client'
      path: '/add-client'
      fullPath: '/practitioner/app/add-client'
      preLoaderRoute: typeof PractitionerAppAddClientRouteImport
      parentRoute: typeof PractitionerAppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/app/yves': {
      id: '/client/app/yves'
      path: '/yves'
      fullPath: '/client/app/yves'
      preLoaderRoute: typeof ClientAppYvesRouteImport
      parentRoute: typeof ClientAppRoute
    }
    '/client/app/timeline': {
      id: '/client/app/timeline'
      path: '/timeline'
      fullPath: '/client/app/timeline'
      preLoaderRoute: typeof ClientAppTimelineRouteImport
      parentRoute: typeof ClientAppRoute
    }
    '/client/app/progress': {
      id: '/client/app/progress'
      path: '/progress'
      fullPath: '/client/app/progress'
      preLoaderRoute: typeof ClientAppProgressRouteImport
      parentRoute: typeof ClientAppRoute
    }
    '/client/app/profile': {
      id: '/client/app/profile'
      path: '/profile'
      fullPath: '/client/app/profile'
      preLoaderRoute: typeof ClientAppProfileRouteImport
      parentRoute: typeof ClientAppRoute
    }
    '/client/app/checkin': {
      id: '/client/app/checkin'
      path: '/checkin'
      fullPath: '/client/app/checkin'
      preLoaderRoute: typeof ClientAppCheckinRouteImport
      parentRoute: typeof ClientAppRoute
    }
    '/api/public/triage-query': {
      id: '/api/public/triage-query'
      path: '/api/public/triage-query'
      fullPath: '/api/public/triage-query'
      preLoaderRoute: typeof ApiPublicTriageQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/app/settings': {
      id: '/admin/app/settings'
      path: '/settings'
      fullPath: '/admin/app/settings'
      preLoaderRoute: typeof AdminAppSettingsRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/app/programs': {
      id: '/admin/app/programs'
      path: '/programs'
      fullPath: '/admin/app/programs'
      preLoaderRoute: typeof AdminAppProgramsRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/app/practitioners': {
      id: '/admin/app/practitioners'
      path: '/practitioners'
      fullPath: '/admin/app/practitioners'
      preLoaderRoute: typeof AdminAppPractitionersRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/app/grading': {
      id: '/admin/app/grading'
      path: '/grading'
      fullPath: '/admin/app/grading'
      preLoaderRoute: typeof AdminAppGradingRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/app/dashboard': {
      id: '/admin/app/dashboard'
      path: '/dashboard'
      fullPath: '/admin/app/dashboard'
      preLoaderRoute: typeof AdminAppDashboardRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/app/clients': {
      id: '/admin/app/clients'
      path: '/clients'
      fullPath: '/admin/app/clients'
      preLoaderRoute: typeof AdminAppClientsRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/app/alerts': {
      id: '/admin/app/alerts'
      path: '/alerts'
      fullPath: '/admin/app/alerts'
      preLoaderRoute: typeof AdminAppAlertsRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/practitioner/app/client-detail/$clientId': {
      id: '/practitioner/app/client-detail/$clientId'
      path: '/client-detail/$clientId'
      fullPath: '/practitioner/app/client-detail/$clientId'
      preLoaderRoute: typeof PractitionerAppClientDetailClientIdRouteImport
      parentRoute: typeof PractitionerAppRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/nightly-risk-analysis': {
      id: '/api/public/hooks/nightly-risk-analysis'
      path: '/api/public/hooks/nightly-risk-analysis'
      fullPath: '/api/public/hooks/nightly-risk-analysis'
      preLoaderRoute: typeof ApiPublicHooksNightlyRiskAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/checkin-reminders': {
      id: '/api/public/hooks/checkin-reminders'
      path: '/api/public/hooks/checkin-reminders'
      fullPath: '/api/public/hooks/checkin-reminders'
      preLoaderRoute: typeof ApiPublicHooksCheckinRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/app/practitioner/$practitionerId': {
      id: '/admin/app/practitioner/$practitionerId'
      path: '/practitioner/$practitionerId'
      fullPath: '/admin/app/practitioner/$practitionerId'
      preLoaderRoute: typeof AdminAppPractitionerPractitionerIdRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/app/client-detail/$clientId': {
      id: '/admin/app/client-detail/$clientId'
      path: '/client-detail/$clientId'
      fullPath: '/admin/app/client-detail/$clientId'
      preLoaderRoute: typeof AdminAppClientDetailClientIdRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/api/public/wearables/polar/callback': {
      id: '/api/public/wearables/polar/callback'
      path: '/api/public/wearables/polar/callback'
      fullPath: '/api/public/wearables/polar/callback'
      preLoaderRoute: typeof ApiPublicWearablesPolarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wearables/oura/webhook': {
      id: '/api/public/wearables/oura/webhook'
      path: '/api/public/wearables/oura/webhook'
      fullPath: '/api/public/wearables/oura/webhook'
      preLoaderRoute: typeof ApiPublicWearablesOuraWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wearables/oura/callback': {
      id: '/api/public/wearables/oura/callback'
      path: '/api/public/wearables/oura/callback'
      fullPath: '/api/public/wearables/oura/callback'
      preLoaderRoute: typeof ApiPublicWearablesOuraCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wearables/garmin/webhook': {
      id: '/api/public/wearables/garmin/webhook'
      path: '/api/public/wearables/garmin/webhook'
      fullPath: '/api/public/wearables/garmin/webhook'
      preLoaderRoute: typeof ApiPublicWearablesGarminWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wearables/garmin/callback': {
      id: '/api/public/wearables/garmin/callback'
      path: '/api/public/wearables/garmin/callback'
      fullPath: '/api/public/wearables/garmin/callback'
      preLoaderRoute: typeof ApiPublicWearablesGarminCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminAppRouteChildren {
  AdminAppAlertsRoute: typeof AdminAppAlertsRoute
  AdminAppClientsRoute: typeof AdminAppClientsRoute
  AdminAppDashboardRoute: typeof AdminAppDashboardRoute
  AdminAppGradingRoute: typeof AdminAppGradingRoute
  AdminAppPractitionersRoute: typeof AdminAppPractitionersRoute
  AdminAppProgramsRoute: typeof AdminAppProgramsRoute
  AdminAppSettingsRoute: typeof AdminAppSettingsRoute
  AdminAppClientDetailClientIdRoute: typeof AdminAppClientDetailClientIdRoute
  AdminAppPractitionerPractitionerIdRoute: typeof AdminAppPractitionerPractitionerIdRoute
}

const AdminAppRouteChildren: AdminAppRouteChildren = {
  AdminAppAlertsRoute: AdminAppAlertsRoute,
  AdminAppClientsRoute: AdminAppClientsRoute,
  AdminAppDashboardRoute: AdminAppDashboardRoute,
  AdminAppGradingRoute: AdminAppGradingRoute,
  AdminAppPractitionersRoute: AdminAppPractitionersRoute,
  AdminAppProgramsRoute: AdminAppProgramsRoute,
  AdminAppSettingsRoute: AdminAppSettingsRoute,
  AdminAppClientDetailClientIdRoute: AdminAppClientDetailClientIdRoute,
  AdminAppPractitionerPractitionerIdRoute:
    AdminAppPractitionerPractitionerIdRoute,
}

const AdminAppRouteWithChildren = AdminAppRoute._addFileChildren(
  AdminAppRouteChildren,
)

interface ClientAppRouteChildren {
  ClientAppCheckinRoute: typeof ClientAppCheckinRoute
  ClientAppProfileRoute: typeof ClientAppProfileRoute
  ClientAppProgressRoute: typeof ClientAppProgressRoute
  ClientAppTimelineRoute: typeof ClientAppTimelineRoute
  ClientAppYvesRoute: typeof ClientAppYvesRoute
  ClientAppIndexRoute: typeof ClientAppIndexRoute
}

const ClientAppRouteChildren: ClientAppRouteChildren = {
  ClientAppCheckinRoute: ClientAppCheckinRoute,
  ClientAppProfileRoute: ClientAppProfileRoute,
  ClientAppProgressRoute: ClientAppProgressRoute,
  ClientAppTimelineRoute: ClientAppTimelineRoute,
  ClientAppYvesRoute: ClientAppYvesRoute,
  ClientAppIndexRoute: ClientAppIndexRoute,
}

const ClientAppRouteWithChildren = ClientAppRoute._addFileChildren(
  ClientAppRouteChildren,
)

interface PractitionerAppRouteChildren {
  PractitionerAppAddClientRoute: typeof PractitionerAppAddClientRoute
  PractitionerAppAlertsRoute: typeof PractitionerAppAlertsRoute
  PractitionerAppDashboardRoute: typeof PractitionerAppDashboardRoute
  PractitionerAppInsightsRoute: typeof PractitionerAppInsightsRoute
  PractitionerAppProfileRoute: typeof PractitionerAppProfileRoute
  PractitionerAppProgramQueueRoute: typeof PractitionerAppProgramQueueRoute
  PractitionerAppSettingsRoute: typeof PractitionerAppSettingsRoute
  PractitionerAppClientDetailClientIdRoute: typeof PractitionerAppClientDetailClientIdRoute
}

const PractitionerAppRouteChildren: PractitionerAppRouteChildren = {
  PractitionerAppAddClientRoute: PractitionerAppAddClientRoute,
  PractitionerAppAlertsRoute: PractitionerAppAlertsRoute,
  PractitionerAppDashboardRoute: PractitionerAppDashboardRoute,
  PractitionerAppInsightsRoute: PractitionerAppInsightsRoute,
  PractitionerAppProfileRoute: PractitionerAppProfileRoute,
  PractitionerAppProgramQueueRoute: PractitionerAppProgramQueueRoute,
  PractitionerAppSettingsRoute: PractitionerAppSettingsRoute,
  PractitionerAppClientDetailClientIdRoute:
    PractitionerAppClientDetailClientIdRoute,
}

const PractitionerAppRouteWithChildren = PractitionerAppRoute._addFileChildren(
  PractitionerAppRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketingRoute: MarketingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SocialRoute: SocialRoute,
  SupportRoute: SupportRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminAppRoute: AdminAppRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ClientAppRoute: ClientAppRouteWithChildren,
  ClientLoginRoute: ClientLoginRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PractitionerAppRoute: PractitionerAppRouteWithChildren,
  PractitionerLoginRoute: PractitionerLoginRoute,
  PractitionerOnboardingRoute: PractitionerOnboardingRoute,
  PractitionerPendingRoute: PractitionerPendingRoute,
  PractitionerSignupRoute: PractitionerSignupRoute,
  ApiPublicTriageQueryRoute: ApiPublicTriageQueryRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksCheckinRemindersRoute: ApiPublicHooksCheckinRemindersRoute,
  ApiPublicHooksNightlyRiskAnalysisRoute:
    ApiPublicHooksNightlyRiskAnalysisRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicWearablesGarminCallbackRoute: ApiPublicWearablesGarminCallbackRoute,
  ApiPublicWearablesGarminWebhookRoute: ApiPublicWearablesGarminWebhookRoute,
  ApiPublicWearablesOuraCallbackRoute: ApiPublicWearablesOuraCallbackRoute,
  ApiPublicWearablesOuraWebhookRoute: ApiPublicWearablesOuraWebhookRoute,
  ApiPublicWearablesPolarCallbackRoute: ApiPublicWearablesPolarCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
