/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PractitionerOnboardingRouteImport } from './routes/practitioner.onboarding'
import { Route as PractitionerLoginRouteImport } from './routes/practitioner.login'
import { Route as PractitionerAppRouteImport } from './routes/practitioner.app'
import { Route as ClientLoginRouteImport } from './routes/client.login'
import { Route as ClientAppRouteImport } from './routes/client.app'
import { Route as ClientAppIndexRouteImport } from './routes/client.app.index'
import { Route as PractitionerAppDashboardRouteImport } from './routes/practitioner.app.dashboard'
import { Route as ClientAppYvesRouteImport } from './routes/client.app.yves'
import { Route as ClientAppTimelineRouteImport } from './routes/client.app.timeline'
import { Route as ClientAppProgressRouteImport } from './routes/client.app.progress'
import { Route as ClientAppCheckinRouteImport } from './routes/client.app.checkin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionerOnboardingRoute = PractitionerOnboardingRouteImport.update({
  id: '/practitioner/onboarding',
  path: '/practitioner/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionerLoginRoute = PractitionerLoginRouteImport.update({
  id: '/practitioner/login',
  path: '/practitioner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionerAppRoute = PractitionerAppRouteImport.update({
  id: '/practitioner/app',
  path: '/practitioner/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client/login',
  path: '/client/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAppRoute = ClientAppRouteImport.update({
  id: '/client/app',
  path: '/client/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAppIndexRoute = ClientAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientAppRoute,
} as any)
const PractitionerAppDashboardRoute =
  PractitionerAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => PractitionerAppRoute,
  } as any)
const ClientAppYvesRoute = ClientAppYvesRouteImport.update({
  id: '/yves',
  path: '/yves',
  getParentRoute: () => ClientAppRoute,
} as any)
const ClientAppTimelineRoute = ClientAppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ClientAppRoute,
} as any)
const ClientAppProgressRoute = ClientAppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ClientAppRoute,
} as any)
const ClientAppCheckinRoute = ClientAppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => ClientAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client/app': typeof ClientAppRouteWithChildren
  '/client/login': typeof ClientLoginRoute
  '/practitioner/app': typeof PractitionerAppRouteWithChildren
  '/practitioner/login': typeof PractitionerLoginRoute
  '/practitioner/onboarding': typeof PractitionerOnboardingRoute
  '/client/app/checkin': typeof ClientAppCheckinRoute
  '/client/app/progress': typeof ClientAppProgressRoute
  '/client/app/timeline': typeof ClientAppTimelineRoute
  '/client/app/yves': typeof ClientAppYvesRoute
  '/practitioner/app/dashboard': typeof PractitionerAppDashboardRoute
  '/client/app/': typeof ClientAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client/login': typeof ClientLoginRoute
  '/practitioner/app': typeof PractitionerAppRouteWithChildren
  '/practitioner/login': typeof PractitionerLoginRoute
  '/practitioner/onboarding': typeof PractitionerOnboardingRoute
  '/client/app/checkin': typeof ClientAppCheckinRoute
  '/client/app/progress': typeof ClientAppProgressRoute
  '/client/app/timeline': typeof ClientAppTimelineRoute
  '/client/app/yves': typeof ClientAppYvesRoute
  '/practitioner/app/dashboard': typeof PractitionerAppDashboardRoute
  '/client/app': typeof ClientAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client/app': typeof ClientAppRouteWithChildren
  '/client/login': typeof ClientLoginRoute
  '/practitioner/app': typeof PractitionerAppRouteWithChildren
  '/practitioner/login': typeof PractitionerLoginRoute
  '/practitioner/onboarding': typeof PractitionerOnboardingRoute
  '/client/app/checkin': typeof ClientAppCheckinRoute
  '/client/app/progress': typeof ClientAppProgressRoute
  '/client/app/timeline': typeof ClientAppTimelineRoute
  '/client/app/yves': typeof ClientAppYvesRoute
  '/practitioner/app/dashboard': typeof PractitionerAppDashboardRoute
  '/client/app/': typeof ClientAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client/app'
    | '/client/login'
    | '/practitioner/app'
    | '/practitioner/login'
    | '/practitioner/onboarding'
    | '/client/app/checkin'
    | '/client/app/progress'
    | '/client/app/timeline'
    | '/client/app/yves'
    | '/practitioner/app/dashboard'
    | '/client/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client/login'
    | '/practitioner/app'
    | '/practitioner/login'
    | '/practitioner/onboarding'
    | '/client/app/checkin'
    | '/client/app/progress'
    | '/client/app/timeline'
    | '/client/app/yves'
    | '/practitioner/app/dashboard'
    | '/client/app'
  id:
    | '__root__'
    | '/'
    | '/client/app'
    | '/client/login'
    | '/practitioner/app'
    | '/practitioner/login'
    | '/practitioner/onboarding'
    | '/client/app/checkin'
    | '/client/app/progress'
    | '/client/app/timeline'
    | '/client/app/yves'
    | '/practitioner/app/dashboard'
    | '/client/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientAppRoute: typeof ClientAppRouteWithChildren
  ClientLoginRoute: typeof ClientLoginRoute
  PractitionerAppRoute: typeof PractitionerAppRouteWithChildren
  PractitionerLoginRoute: typeof PractitionerLoginRoute
  PractitionerOnboardingRoute: typeof PractitionerOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioner/onboarding': {
      id: '/practitioner/onboarding'
      path: '/practitioner/onboarding'
      fullPath: '/practitioner/onboarding'
      preLoaderRoute: typeof PractitionerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioner/login': {
      id: '/practitioner/login'
      path: '/practitioner/login'
      fullPath: '/practitioner/login'
      preLoaderRoute: typeof PractitionerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioner/app': {
      id: '/practitioner/app'
      path: '/practitioner/app'
      fullPath: '/practitioner/app'
      preLoaderRoute: typeof PractitionerAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/login': {
      id: '/client/login'
      path: '/client/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/app': {
      id: '/client/app'
      path: '/client/app'
      fullPath: '/client/app'
      preLoaderRoute: typeof ClientAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/app/': {
      id: '/client/app/'
      path: '/'
      fullPath: '/client/app/'
      preLoaderRoute: typeof ClientAppIndexRouteImport
      parentRoute: typeof ClientAppRoute
    }
    '/practitioner/app/dashboard': {
      id: '/practitioner/app/dashboard'
      path: '/dashboard'
      fullPath: '/practitioner/app/dashboard'
      preLoaderRoute: typeof PractitionerAppDashboardRouteImport
      parentRoute: typeof PractitionerAppRoute
    }
    '/client/app/yves': {
      id: '/client/app/yves'
      path: '/yves'
      fullPath: '/client/app/yves'
      preLoaderRoute: typeof ClientAppYvesRouteImport
      parentRoute: typeof ClientAppRoute
    }
    '/client/app/timeline': {
      id: '/client/app/timeline'
      path: '/timeline'
      fullPath: '/client/app/timeline'
      preLoaderRoute: typeof ClientAppTimelineRouteImport
      parentRoute: typeof ClientAppRoute
    }
    '/client/app/progress': {
      id: '/client/app/progress'
      path: '/progress'
      fullPath: '/client/app/progress'
      preLoaderRoute: typeof ClientAppProgressRouteImport
      parentRoute: typeof ClientAppRoute
    }
    '/client/app/checkin': {
      id: '/client/app/checkin'
      path: '/checkin'
      fullPath: '/client/app/checkin'
      preLoaderRoute: typeof ClientAppCheckinRouteImport
      parentRoute: typeof ClientAppRoute
    }
  }
}

interface ClientAppRouteChildren {
  ClientAppCheckinRoute: typeof ClientAppCheckinRoute
  ClientAppProgressRoute: typeof ClientAppProgressRoute
  ClientAppTimelineRoute: typeof ClientAppTimelineRoute
  ClientAppYvesRoute: typeof ClientAppYvesRoute
  ClientAppIndexRoute: typeof ClientAppIndexRoute
}

const ClientAppRouteChildren: ClientAppRouteChildren = {
  ClientAppCheckinRoute: ClientAppCheckinRoute,
  ClientAppProgressRoute: ClientAppProgressRoute,
  ClientAppTimelineRoute: ClientAppTimelineRoute,
  ClientAppYvesRoute: ClientAppYvesRoute,
  ClientAppIndexRoute: ClientAppIndexRoute,
}

const ClientAppRouteWithChildren = ClientAppRoute._addFileChildren(
  ClientAppRouteChildren,
)

interface PractitionerAppRouteChildren {
  PractitionerAppDashboardRoute: typeof PractitionerAppDashboardRoute
}

const PractitionerAppRouteChildren: PractitionerAppRouteChildren = {
  PractitionerAppDashboardRoute: PractitionerAppDashboardRoute,
}

const PractitionerAppRouteWithChildren = PractitionerAppRoute._addFileChildren(
  PractitionerAppRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientAppRoute: ClientAppRouteWithChildren,
  ClientLoginRoute: ClientLoginRoute,
  PractitionerAppRoute: PractitionerAppRouteWithChildren,
  PractitionerLoginRoute: PractitionerLoginRoute,
  PractitionerOnboardingRoute: PractitionerOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
